### ISSUE TITLE
`"Starting Manim..."` hangs -- if we quit right after starting

### ISSUE THREAD

**Issue by VladimirFokow** [Manim-Notebook/manim-notebook#83]
## Steps to reproduce:

```py
from manimlib import *

class MyScene(Scene):
    def construct(self):
        ## Test 1
        circle = Circle()
        self.play(ShowCreation(circle))
```

- place cursor on any of the lines among: 5-8
- "Manim Notebook: Start scene at cursor"
- BEFORE IT finishes starting: "Manim Notebook: Quit preview"

---> the "Starting Manim..." notification hangs

(this happens only sometimes..)

<br />

## Log 1:

[Manim Notebook.log](https://github.com/user-attachments/files/17619830/Manim.Notebook.log)

Here I made 4 attempts to:
- start scene (with a shortcut)
- then quit it (with a shortcut)

Only on the last attempt the bug (the notification hang) happened.

(in the meantime I show and hide the VSCode terminal several times with a shortcut)

https://github.com/user-attachments/assets/d5c9b785-9acc-42e9-bb12-51564a403a18

**Comment by Splines** [comment]
Minimal reproduction log: [Manim Notebook.log](https://github.com/user-attachments/files/17691906/Manim.Notebook.log)
