### ISSUE TITLE
`"Starting Manim..."` hangs -- if we start on class name

### ISSUE THREAD

**Issue by VladimirFokow** [Manim-Notebook/manim-notebook#84]
## Steps to reproduce:

```py
from manimlib import *

class MyScene(Scene):
    def construct(self):
        ## Test 1
        circle = Circle()
        self.play(ShowCreation(circle))
```

- put cursor on line 3 (line `class MyScene(Scene):`)
- run "Manim Notebook: Start scene at cursor"

The scene starts (as expected)
(with the command `manimgl filename.py className`) <-- note no `-se lineNumber` here, 
&nbsp;&nbsp;&nbsp;&nbsp;   so the whole scene will be played,
&nbsp;&nbsp;&nbsp;&nbsp;   and then the terminal will be left in the interactive mode.

The Problem:
Notification `"Starting Manim..."` hangs.

(I didn't record the logs - I think it will be reproducible without them)

**Comment by Splines** [comment]
Yes, can reproduce, thanks for the report.
