### ISSUE TITLE
Detect Manim version

### ISSUE THREAD

**Issue by Splines** [Manim-Notebook/manim-notebook#97]
It'd be beneficial to know which Manim version the user is running to enable/disable some features, e.g. the `reload()` command is only implemented in the most recent version (not even a released version, right now just at the `master` branch).

**Comment by Splines** [comment]
Then only enable features like `reload()`, `focus()` and the `--autoreload` flag only for appropriate ManimGL versions.

**Comment by Splines** [comment]
Also include this version in the log file (`manimgl --version`) as well as the Python version `python --version`.

**Comment by bhoov** [comment]
> Idea: We could also fetch the current Manim version from GitHub (and if that fetch was successful) & if that version online is newer than the current version that the user has installed, show a notification that they might want to update ManimGL.

Nice idea! But let's not make it obtrusive because some will intentionally keep their manim version compatible with the existing project.
